### A simple get request to the test endpoint. No need for login
GET {{url}}/auth/test/

### Create a new user - this one will only get a USER role by default
POST {{url}}/auth/register/

{
    "username": "tenny",
    "password": "test123"
}

###
POST {{url}}/auth/login/

{
    "username": "tenny",
    "password": "test123"
}

> {%
    client.global.set("jwt_token", response.body.token);
    console.log("JWT Token:", client.global.get("jwt_token"));
%}

### Add admin role to user
POST {{url}}/auth/user/addrole/
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
    "role": "admin"
}




### TOWN

### Populate datbase with towns
GET {{url}}/town/populate/


### Get all towns including shops
GET {{url}}/town/


### Get specific town by ID (ID 1 in this example)
GET {{url}}/town/1


### Update specific town by ID
PUT http://localhost:7070/api/town/1
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "name": "Updated town Name",
  "description": "Updated town description",
  "features": "Updated town features"
}


### Create a new town
POST {{url}}/town/
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "name": "New Town Name",
  "description": "New town description",
  "features": "New town features"
}


### Delete a town by ID including shops (ID 1 in this example)
DELETE {{url}}/town/1
Content-Type: application/json
Authorization: Bearer {{jwt_token}}


// NPC API

### Populate database with NPCs
GET {{url}}/npc/populate/


### Get all NPCs
GET {{url}}/npc/


### Get specific NPC by ID (example: ID 1)
GET {{url}}/npc/1


### Update specific NPC by ID
PUT http://localhost:7070/api/npc/1
Content-Type: application/json

{
  "name": "Updated NPC Name",
  "race": "HALFELF",
  "professions": "Updated Profession(s)",
  "description": "Updated description"
}


### Create a new NPC
POST {{url}}/npc/
Content-Type: application/json

{
  "name": "New NPC Name",
  "race": "HUMAN",
  "professions": "Blacksmith",
  "description": "A skilled blacksmith living in the capital city."
}


### Delete an NPC by ID (example: ID 2)
DELETE {{url}}/npc/2

// Shop API

### Populate datbase with shops
GET {{url}}/shop/populate/


### Get all shops
GET {{url}}/shop/


### Get specific shop by ID (ID 1 in this example)
GET {{url}}/shop/1


### Update specific shop by ID
PUT http://localhost:7070/api/shop/1
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "name": "Updated shop Name",
  "shoptype": "WEAPONSMITH",
  "owner": "Updated shop features"
}


### Create a new shop
POST {{url}}/shop/
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "name": "New shop Name",
  "shoptype": "BLACKSMITH",
  "owner": "New shop features"
}


### Delete a shop by ID (ID 1 in this example)
DELETE {{url}}/shop/1
Content-Type: application/json
Authorization: Bearer {{jwt_token}}